"""add is_deleted to session

Revision ID: 9df6e0f80afb
Revises: ddc25974eaa3
Create Date: 2026-01-13 18:31:36.245784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df6e0f80afb'
down_revision: Union[str, Sequence[str], None] = 'ddc25974eaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE session SET is_deleted = false")
    op.alter_column('session', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'is_deleted')
    # ### end Alembic commands ###
