"""Add goals and pitfalls to curriculum

Revision ID: ddc25974eaa3
Revises: c7c0a043b2cb
Create Date: 2026-01-13 14:46:29.858663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ddc25974eaa3"
down_revision: Union[str, Sequence[str], None] = "c7c0a043b2cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "curriculum",
        sa.Column("learning_goals", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "curriculum",
        sa.Column(
            "common_pitfalls", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("curriculum", "common_pitfalls")
    op.drop_column("curriculum", "learning_goals")
    # ### end Alembic commands ###
